### ISSUE TITLE
Make more newbie friendly

### ISSUE THREAD

**Issue by osg** [speric/kindle-highlights#4]
Happy to pair with someone on how to make this more newbie friendly. Interested in this gem, but cannot get it to work.

Likely other polyglots who use highlights for learning languages are interested and are even less technical than I am. Shout out if you are interested in making this more broadly accessible. Will to help with doing that. Just gotta get it to work first...

**Comment by speric** [comment]
@opensourcegrrrl Sorry to hear that; what problems are you having?

**Comment by osg** [comment]
`mr_kite` threw me off as a profile name within Amazon. Yes, the comment says Amazon credentials, but somehow I was not sure that this was a password whilst looking at the command. Also, made it gender neutral in my PR.

**Comment by osg** [comment]
Got output after realizing that!

Lemme run through the rest of this usage statement...

**Comment by osg** [comment]
See some output, of which this is a sample:

```
"B007Z8VKSQ"=>"A Modern English-Chinese Dictionary (现代英汉词典)", "B0044XUWM0"=>"Modismos / Idioms", "B00T11GNUA"=>"The Monkey's Paw: Mandarin Companion Graded Readers: Level 1, Simplified Chinese Edition", "B0043D2E22"=>"Natural Language Processing with Python", "B003ODIZL6"=>"The New Oxford American Dictionary", "B0053VMNY2"=>"The New Oxford American Dictionary", "B00KFGCD1I"=>"Nicely Said: Writing for the Web with Style and Purpose (Voices That Matter)", "B000OT8GV2"=>"The No Asshole Rule: Building a Civilized Workplace and Surviving One That Isn't", "B00LVRWB08"=>"Notetaking for Consecutive Interpreting: A Short Course (Translation Practices Explained)",
```

How can I get this output to be more human readable?

By that I mean:

```
"B007Z8VKSQ"=>"A Modern English-Chinese Dictionary (现代英汉词典)",
"B0044XUWM0"=>"Modismos / Idioms",
"B00T11GNUA"=>"The Monkey's Paw: Mandarin Companion Graded Readers: Level 1, Simplified Chinese Edition",
"B0043D2E22"=>"Natural Language Processing with Python",
"B003ODIZL6"=>"The New Oxford American Dictionary",
"B0053VMNY2"=>"The New Oxford American Dictionary",
"B00KFGCD1I"=>"Nicely Said: Writing for the Web with Style and Purpose (Voices That Matter)",
"B000OT8GV2"=>"The No Asshole Rule: Building a Civilized Workplace and Surviving One That Isn't",
"B00LVRWB08"=>"Notetaking for Consecutive Interpreting: A Short Course (Translation Practices Explained)",
```

**Comment by osg** [comment]
If it matters at all, I am on an X1 Carbon ThinkPad running Ubuntu 14.04 LTS.

**Comment by osg** [comment]
Also, the error message that I encountered first when I had incorrectly input my profile name as opposed to my password was as follows:

```
ursula@ja-genau:~$ irb
irb(main):001:0> require 'kindle_highlights'
=> true
irb(main):002:0> kindle = KindleHighlights::Client.new("[omitted]", "[omitted-too]")
NoMethodError: undefined method `[]' for nil:NilClass
    from /home/ursula/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/mechanize-2.7.4/lib/mechanize.rb:372:in `click'
    from /home/ursula/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/kindle-highlights-0.0.8/lib/kindle_highlights/client.rb:30:in `load_books_from_kindle_account'
    from /home/ursula/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/kindle-highlights-0.0.8/lib/kindle_highlights/client.rb:10:in `initialize'
    from (irb):2:in `new'
    from (irb):2
    from /home/ursula/.rbenv/versions/2.1.0/bin/irb:11:in `<main>'
```

, where `[omitted]` is my email address associated with my Amazon account, and `[omitted-too]` is my Kindle highlights profile.

**Comment by speric** [comment]
There are a couple of Ruby gems that will make Ruby hashes look nicer in the console. This is a helpful thread: http://stackoverflow.com/questions/8842546/best-way-to-pretty-print-a-hash

I mostly use yaml for situations like this, so if the variable which points to the hash returned from Amazon is named `my_books`, in a Ruby console you can do:

``` ruby
$ y my_books
```

And it should print out the hash in a nicer format. In any case, a more human-readable output is beyond the scope of this gem, as it concerns console functionality and not gem functionality.

**Comment by speric** [comment]
@opensourcegrrrl
